sudo: required

git:
  depth: 9999

language: c

matrix:
  include:
  - os: linux
    compiler: gcc
    services:
      - docker
    before_deploy: 
      - git config --local user.name "Open Identity Platform Community" && git config --local user.email "open-identity-platform-openam@googlegroups.com"
      - git checkout -f $TRAVIS_BRANCH
      - git tag -f $git_version && git tag -d $git_version
      - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git >/dev/null 2>&1
      - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git $git_version >/dev/null 2>&1
    deploy:
      provider: releases
      draft: false
      prerelease: false
      target_commitish: $(git rev-list -n 1 $git_version)
      tag_name: $git_version
      name: $git_version
      body: "compare: $(git rev-list -n 1 $git_version_last)...$(git rev-list -n 1 $git_version)"
      api_key:
       secure: l0E8q0lb5cKNAZzvppWs6Jx8e6iq+kJvoEqk0/JKH1KV7cUdNzEjS/QORHeswjl0JLeWIsThN3A83ZO7bAM1jarfTeEQpSTxjFerW7S5dvpX8EmRGRLC6POqm8Y/YdT88QqSLwhmTHIdBo5EwJXrx1qMFHtfRfU3ji7U8mPRYzIdwXc0yWBDPj5FAw9olWZSldW9jegrDQSpK7ghZ4FNjqh7nqOCBkOKZdDvGlemX8lVK/Am1oO/jaLHYsIZgFEXE0WvAw9sZbCJfwxCv6IYn/RFWDXN6CHLUz/oXmhhZwrZN/As/0jQwvkHNRY6Hyz7um+a4eXcvqbid1CiO316Pj5yNMb1hyqN1iQWfy4acxgFV/J+wMOHsnIJHvJKoMRCCCa46ZPHAThZljVR7/7D8VB7PP0wpfod4HzoZ6/D5oMKOLzTvIWOpOoFXY5Kx/ji+g5o4taVRkINoYTshAUt7ob4/Et/+qeUzisxDizDXgep3B3t4BNl4a1M0e30/USgdjlEZ+D8dAFGO/IxIh+kd29OTf1Wqeg73CxEg0NSdzxIJP4ls8Zdw9UTTW9Fsv6SG7YjmYa1ISne5/mNTcdeBepO8YFdGUXCnBI0cjv1hTqwMRzGK8s98DdiuDu9YWy04mbklF7Sj0jgnpA3NQivIKyVEr+cA49pf5v6APxRuQs=
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file: 
        - "*.zip"
      on:
        repo: OpenIdentityPlatform/OpenAM-Web-Agents
        tags: false
        branch: 
          - master
          - travis
    after_deploy:
      - echo 'after_deploy'
      - echo 'build and push Docker'
      -   #docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      -   #docker build ./openam-distribution/openam-distribution-docker/target -t $DOCKER_USERNAME/openam -t $DOCKER_USERNAME/openam:$git_version
      -   #docker push $DOCKER_USERNAME/openam-apache:$git_version
      -   #docker push $DOCKER_USERNAME/openam-apache
  - os: linux
    compiler: clang

notifications:
  email:
  - open-identity-platform-openam@googlegroups.com

branches:
  except:
    - /[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - sudo apt-get install -qq -y libpcre3-dev libbz2-dev

before_install:
  - date -u
  - uname -a
  - sudo apt-get install -qq -y libpcre3-dev libbz2-dev
  - git fetch -t
  - export git_version_last="$(git describe --abbrev=0 --tags --always)"
  - export git_version="$(echo $git_version_last | awk -F . '{ printf "%d.%d.%d", $1,$2,$3 + 1}')"
  - env | sort
  - git log `git describe --tags --abbrev=0 HEAD^ --always`..HEAD --oneline 
  
install:
  - ./prepare-apache.sh

script:
  - sed -i 's#4\.1\.0#'"${git_version}"'#g' Makefile
  - make apache22zip && mv build/*.zip .
  - make apachezip && mv build/*.zip .

after_failure:
  - echo 'remove build commits'
  - git reset --hard $TRAVIS_COMMIT
  - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git >/dev/null 2>&1
